export interface GalleryImage {
  src: string;
  alt: string;
}

/** Orden fijo: 1–11 según brief del cliente; el resto a continuación */
export const galleryImages: GalleryImage[] = [
  // 1–11 (orden cliente)
  { src: "/assets/gallery/25imagen.jpg", alt: "Cóctel Dream Drinks con garnish de cítrico" },
  { src: "/assets/gallery/41imagen.jpeg", alt: "Bartender preparando cóctel en la barra" },
  { src: "/assets/gallery/30imagen.png", alt: "Servicio de cóctel en vaso con hielo" },
  { src: "/assets/gallery/11imagen.jpg", alt: "Invitado disfrutando el servicio de barra" },
  { src: "/assets/gallery/33imagen.jpg", alt: "Servicio de shots en evento" },
  { src: "/assets/gallery/15imagen.jpg", alt: "Cóctel Dream Drinks ofrecido al invitado" },
  { src: "/assets/gallery/23imagen.jpg", alt: "Cóctel premium con etiqueta Dream Drinks" },
  { src: "/assets/gallery/39imagen.jpeg", alt: "Barra ondulado dorada Dream Drinks" },
  { src: "/assets/gallery/14imagen.jpg", alt: "Cócteles en formato individual" },
  { src: "/assets/gallery/19imagen.jpg", alt: "Ambiente de evento con barra Dream Drinks" },
  { src: "/assets/gallery/31imagen.jpg", alt: "Bartender sirviendo shots en el evento" },
  // Resto
  { src: "/assets/gallery/1imagen.jpg", alt: "Detalle de barra iluminada" },
  { src: "/assets/gallery/2imagen.jpg", alt: "Servicio de whisky en barra premium" },
  { src: "/assets/gallery/3imagen.jpg", alt: "Barra isla Dream Drinks" },
  { src: "/assets/gallery/4imagen.jpg", alt: "Montaje de barra para evento" },
  { src: "/assets/gallery/5imagen.jpg", alt: "Insumos y garnishes de coctelería" },
  { src: "/assets/gallery/7imagen.jpg", alt: "Celebración en evento" },
  { src: "/assets/gallery/8imagen.jpg", alt: "Pista y celebración" },
  { src: "/assets/gallery/9imagen.jpg", alt: "Fiesta y ambiente Dream Drinks" },
  { src: "/assets/gallery/10imagen.jpg", alt: "Técnica de ahumado en barra" },
  { src: "/assets/gallery/12imagen.jpg", alt: "Detalle de barra y carta" },
  { src: "/assets/gallery/13imagen.jpg", alt: "Barra iluminada con menú" },
  { src: "/assets/gallery/16imagen.jpg", alt: "Presentación de cóctel Dream Drinks" },
  { src: "/assets/gallery/17imagen.jpg", alt: "Bartenders en evento" },
  { src: "/assets/gallery/18imagen.jpg", alt: "Servicio de barra en vivo" },
  { src: "/assets/gallery/20imagen.jpg", alt: "Invitados en el evento" },
  { src: "/assets/gallery/21imagen.jpg", alt: "Barra Gin and Tonics" },
  { src: "/assets/gallery/22imagen.jpg", alt: "Bartender sirviendo cóctel" },
  { src: "/assets/gallery/24imagen.jpg", alt: "Equipo Dream Drinks" },
  { src: "/assets/gallery/26imagen.jpg", alt: "Invitados en la barra" },
  { src: "/assets/gallery/27imagen.jpg", alt: "Preparación de gin tonic" },
  { src: "/assets/gallery/28imagen.jpg", alt: "Entrega de trago en el evento" },
  { src: "/assets/gallery/32imagen.jpg", alt: "Bartender en acción" },
  { src: "/assets/gallery/34imagen.jpg", alt: "Cóctel Dream Drinks Premium" },
  { src: "/assets/gallery/35imagen.jpg", alt: "Bartender agitando coctelera" },
  { src: "/assets/gallery/36imagen.jpg", alt: "Cóctel de autor" },
  { src: "/assets/gallery/37imagen.jpg", alt: "Bandeja de shots" },
  { src: "/assets/gallery/38imagen.jpg", alt: "Preparación de cócteles" },
  { src: "/assets/gallery/40imagen.jpeg", alt: "Barra Dream Drinks en evento nocturno" },
  { src: "/assets/gallery/42imagen.jpeg", alt: "Servicio de spritz" },
  { src: "/assets/gallery/43imagen.jpeg", alt: "Montaje premium Dream Drinks" },
  { src: "/assets/gallery/44imagen.jpeg", alt: "Barra con branding Dream Drinks" },
  { src: "/assets/gallery/45imagen.jpeg", alt: "Evento DreamDrinks 45" },
  { src: "/assets/gallery/46imagen.jpeg", alt: "Evento DreamDrinks 46" },
  { src: "/assets/gallery/47imagen.jpeg", alt: "Evento DreamDrinks 47" },
  { src: "/assets/gallery/coctail.jpg", alt: "Cóctel Dream Drinks Premium" },
  { src: "/assets/gallery/gin.jpg", alt: "Preparación de gin" },
  { src: "/assets/gallery/jager.jpg", alt: "Servicio de shots" },
  { src: "/assets/gallery/cynar.jpg", alt: "Cóctel en preparación" },
  { src: "/assets/gallery/carrito.jpg", alt: "Carrito de barra" },
  { src: "/assets/gallery/cartel.jpg", alt: "Cartel de evento" },
];
